version: "1"

services:
  # Backend (Flask service)
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/GP233b/OE-ZTPI
    branch: frontend  # Adjust this if needed
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile  # Use the Dockerfile in the root for Flask
    envVars:
      - key: FLASK_APP
        value: "main.py"
      - key: FLASK_ENV
        value: "development"
    autoDeployTrigger: commit

  # Frontend (Angular service)
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/GP233b/OE-ZTPI
    branch: frontend  # Adjust this if needed
    plan: free
    region: frankfurt
    dockerfilePath: ./ztp-front/Dockerfile  # Use the Dockerfile inside the ztp-front directory for Angular
    autoDeployTrigger: commit
